- src/shared/constants/dimensions.js
- src/shared/utils/index.js
closes #59
- defined columnLegendHeight
- added columnLegendHeight to showLegend
> [G2M] Legend - fix legend column too tall

- CHANGELOG.md
- README.md
- src/components/bar-chart/index.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/custom-node.js
- src/components/scatter-chart/events.js
- src/components/scatter-chart/index.js
- src/shared/constants/chart-props.js
- src/shared/utils/index.js
- src/stories/scatter.stories.js
Fix for hover, targeting data id instead of fill colour
Closes #66
> Scatter hover fix

- .storybook/main.js
- package.json
- src/components/bar-chart/index.js
- src/components/hooks.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/index.js
- src/shared/constants/chart-props.js
- src/shared/utils/index.js
- src/stories/bar.stories.js
- src/stories/pie.stories.js
- yarn.lock
closes #79 
closes #77 
closes #78 
closes #39
> [G2M] DevOps - add story source module

- README.md
- src/shared/utils/index.js
- src/stories/line.stories.js
> [G2M] Utils - properly pass on valueKey to sort nivo data

- README.md
> [G2M] README - correct scatter/line prop usage

- CHANGELOG.md
- src/components/chart-wrapper/index.js
- stories/responsive-chart-wrapper.js
Closes #100
- chart-wrapper/index.js: included Wrapper styled component
- responsive-chart-wrapper.js: replaced Wrapper with simpler ChartDiv styled component
- CHANGELOG.md: added Wrapper changes and revised
> Wrapper: include in ChartWrapper component

- .eslintrc.js
- CHANGELOG.md
- README.md
- package.json
- src/components/bar-chart/index.js
- src/components/chart-wrapper/index.js
- src/components/legend-symbol/index.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/custom-node.js
- src/components/scatter-chart/index.js
- src/components/tooltip/index.js
- src/shared/constants/title-props.js
- src/shared/utils/index.js
- stories/bar.stories.js
- stories/line.stories.js
- stories/pie.stories.js
- stories/responsive-chart-wrapper.js
- stories/scatter.stories.js
- yarn.lock
> Title component with nivo ResponsiveWrapper

- CHANGELOG.md
- src/components/bar-chart/index.js
- src/components/chart-wrapper/index.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/index.js
- src/components/tooltip/index.js
Adds chart typography styling to tooltip
> Tooltip/typography - pass chart typography style to tooltip component

- src/components/chart-wrapper/index.js
> [G2M] ChartWrapper - useRef and check for titleRef

- CHANGELOG.md
- README.md
- package.json
- src/components/bar-chart/index.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/index.js
- src/components/tooltip/index.js
- src/shared/constants/chart-props.js
- src/shared/utils/index.js
- stories/axis.stories.js
- stories/bar.stories.js
- stories/dynamic-data.stories.js
- stories/legend.stories.js
- stories/line.stories.js
- stories/pie.stories.js
- stories/title.stories.js
- stories/tooltip.stories.js
- stories/typography.stories.js
Adds disableLegend prop to be able to hide chart Legend for a chart.
Fixes topography prop on Tooltip
Reorganizes stories, creating new stories for legend, title, axis, typography, tooltip, dynamic-data.
> Legend/disableLegend, tooltip topography props fix, reorganize stories

- .github/workflows/master.yml
- README.md
- package.json
- src/components/bar-chart/index.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/index.js
- src/shared/utils/index.js
- stories/color.stories.js
- stories/scatter.stories.js
Closes #132
**Fixes:**
1. Fixed applying colors prop as a function for all charts - code logic was still missing after the last PR
2. Added storybooks for color as function for each chart type
3. Pie - removed white divider left when hiding data in legend when we have one slice left at 100 %
4. Added commit-watch to github/workflows master.yml
Before:
After:
> [G2M] Colors prop as function fix; Pie fix for 100% slice white divider left when hiding data in legend

- src/components/d3/gauge-bar.js
- stories/gauge-bar.stories.js
Feature request from: https://eqworks.slack.com/archives/C01TFFLQVB5/p1626201159000200
> [G2M] added ratio adjuster

- .github/workflows/chromatic.yml
- .github/workflows/master.yml
- .github/workflows/npm-alpha.yml
- .github/workflows/npm.yml
- .github/workflows/storybook-deploy.yml
- .gitignore
- package.json
- src/components/bar-chart/index.js
- src/components/legend-symbol/index.js
- src/components/line-chart/index.js
- src/components/pie-chart/index.js
- src/components/scatter-chart/index.js
Chromatic: https://www.chromatic.com/build?appId=60f5a69eddb5b90039b6d17c&number=2
> [G2M] Add chromatic workflow; update node versions in github workflows; fix lint warnings for React hook dep list in nivo charts

- .github/workflows/chromatic.yml
- .github/workflows/master.yml
- .github/workflows/npm-alpha.yml
- .github/workflows/npm.yml
- .github/workflows/storybook-deploy.yml
- package.json
- src/components/plotly/shared/custom-plot.js
- src/components/plotly/shared/legend.js
- src/components/plotly/shared/styles/index.js
- src/components/plotly/shared/styles/legend.js
- src/components/plotly/shared/styles/plot.js
- src/components/plotly/shared/styles/util.js
- yarn.lock
- added dep `lumen-labs` to have access to `getTailwindConfigColor()`
- had to make some adjustments to the workflow files to allow installing the scoped package
- legend is now positioned relatively to the viz, i.e. it will not overlap
- legend styling has generally been changed
- viz size only applies to subplots (defaults to 0.8 otherwise)
Legend styling is still far from perfect. Will keep working on it over time.
> [G2M] Plotly/rework legend

- .github/workflows/chromatic.yml
- .github/workflows/main.yml
- .github/workflows/npm-alpha.yml
- .github/workflows/npm.yml
- .github/workflows/storybook-deploy.yml
- package.json
- src/components/plotly/shared/custom-plot.js
similar to https://github.com/EQWorks/widget-studio/pull/91
> [G2M] devops - nonblocking chromatic build, add/revise yarn cache action usage, default main

- package.json
- src/components/plotly/pyramid-bar/index.js
- src/components/plotly/shared/use-transformed-data.js
- src/util/numeric.js
- stories/plotly/plotly-pyramid-bar.stories.js
- Changed Pyramid chart data manipulation to match other charts logic
- Added numeric formatting for bar & pyramid chart (ex: 10000 -> 10k, 1000000 -> 1M) using d3 formatting
> [G2M] change Pyramid datatransform data access

- package.json
- src/components/plotly/shared/constants/index.js
to temporary disable 
https://user-images.githubusercontent.com/59836949/192872463-38de7dd9-c990-431d-bc58-a12e1b8b0614.mov
> [G2M] Plotly - disable zoom view option

- __tests__/unit/plotly.test.js
- src/components/plotly/bar/index.js
- src/components/plotly/pie/index.js
- src/components/plotly/pyramid-bar/index.js
- src/components/plotly/shared/utils.js
- Separated code into util file to allow for reusability and readability
- Implemented unit testing for functions necessary to generate Plotly graphs
> [G2M] Plotly - implementing unit tests

- __tests__/unit/plotly.test.js
- src/components/plotly/shared/use-transformed-data.js
- src/components/plotly/shared/utils.js
Fixes #194 
- Separated useTransformedData into util
- Implemented unit testing for getObjectByType
> [G2M] plotly - implement transformdData tests

- package.json
- src/components/plotly/bar-line/index.js
- src/components/plotly/bar/index.js
- src/components/plotly/double-line/index.js
- src/components/plotly/line/index.js
- src/components/plotly/pie/index.js
- src/components/plotly/pyramid-bar/index.js
- src/components/plotly/scatter/index.js
- src/components/plotly/shared/custom-plot.js
- src/components/plotly/shared/plot.js
fixes #206 
- Added function in promise when plot is loaded
Tested in widget studio & dashboard. Since there are multiple widgets in each report on the dashboard side a flag or counter will need to be added to match the number of widget present in the report to tell all the widgets are loaded
> [G2M] Plotly - state callback when plot is loaded

- package.json
- src/components/plotly/bar/index.js
- src/components/plotly/shared/utils.js
https://www.notion.so/eqproduct/Fix-custom-axis-label-when-we-have-horizontal-bar-charts-2972072178bd427f951d988e05029dae
> [G2M] plotly-bar - removed auto title axis flip on orientation changes 

- .github/workflows/chromatic.yml
- .github/workflows/main.yml
- .github/workflows/npm-alpha.yml
- .github/workflows/npm.yml
- .github/workflows/storybook-deploy.yml
https://www.notion.so/eqproduct/Chart-System-update-workflows-377f8a4aabb344c6bd70e82060578b23?pvs=4
> [G2M] Github/workflows - update to v3 github actions
